name: test checkout

on:
  push:
    branches:
      - checkout

jobs:
  test-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout quest repository
        uses: actions/checkout@v3
        with:
          repository: parseablehq/quest
          path: quest

      - name: Rename and Upload Result File
        run: |
          cd quest/clickbench
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          cp run_query.sh "result_$SHORT_SHA.csv"
          echo "RESULT_FILE=$(realpath "result_$SHORT_SHA.csv")" >> $GITHUB_ENV
          tree

      - uses: actions/upload-artifact@v3
        with:
          path: ${{ env.RESULT_FILE }}
