name: test checkout

on:
  push:
    branches:
      - checkout

jobs:
  test-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout quest repository
        uses: actions/checkout@v3
        with:
          repository: parseablehq/quest
          path: quest

      - name: Rename and Upload Result File
        run: |
          tree
          cd clickbench
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          cp run_query.sh result_${SHORT_SHA}.csv

      - uses: actions/upload-artifact@v3
        with:
          name: result_${{ github.sha }}
          path: result_${SHORT_SHA}.csv
